; Copy and paste these lines to the IDL command prompt.

setenv, 'CLASSPATH=autoplot.jar'  ; download from http://autoplot.org/latest/autoplot.jar
pm= OBJ_NEW( ) ; like null in Java or None in Jython

url= OBJ_NEW( 'IDLJavaObject$URL', 'java.net.URL', 'https://emfisis.physics.uiowa.edu/events/rbsp-a/misc-support-files/rbspa-half-orbit-periods2.txt' )

DataSetURI= OBJ_NEW( 'IDLJavaObject$Static$DataSetURI', 'org.autoplot.datasource.DataSetURI' )
ff= DataSetURI.downloadResourceAsTempFile(url,pm)
print, ff.toString()

openr, lun, ff.toString(), /get_lun
line = ''

WHILE NOT EOF(lun) DO BEGIN & $
  READF, lun, line & $
  print, line
ENDWHILE

